### ISSUE TITLE
代码理解求助

### ISSUE THREAD

**Issue by billiewalt** [dds2333/GM_nist_sts#1]
想问一下源码里的 Len 是怎么从文件取到长度的 , 望解惑 . 

```
//检测函数
void MainWindow::detect_fun(BitSequence* bits,int len)
{
```

**Comment by dds2333** [comment]
> 
先获取文件字节长度，再乘以8得到比特（位）长度，如下：
<img width="626" alt="Snipaste_2022-04-14_14-41-37" src="https://user-images.githubusercontent.com/48277238/163329453-f0e5c986-7f3b-4bc1-aecf-f48cea39da4a.png">
<img width="622" alt="Snipaste_2022-04-14_14-43-17" src="https://user-images.githubusercontent.com/48277238/163329481-fb745dc1-3789-4410-9ea1-d132f47b9990.png">
@[BillieWalt](https://github.com/BillieWalt)

**Comment by billiewalt** [comment]
感谢回复，信安小白👻在这里谢谢先生了🎈
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年4月14日 下午 2:49
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [dds2333/GM_nist_sts] 代码理解求助 (Issue #1)


先获取文件字节长度，再乘以8得到比特（位）长度，如下：
[Snipaste_2022-04-14_14-41-37]<https://user-images.githubusercontent.com/48277238/163329453-f0e5c986-7f3b-4bc1-aecf-f48cea39da4a.png>
[Snipaste_2022-04-14_14-43-17]<https://user-images.githubusercontent.com/48277238/163329481-fb745dc1-3789-4410-9ea1-d132f47b9990.png>
